### ISSUE TITLE
Some Api path not found ?

### ISSUE THREAD

**Issue by febryardiansyah** [rizalord/komikcast-rest-api#1]
I just tried some endpoints, but it says not found

am i was doing wrong ? or there's something wrong with the api ?
Thanks
![image](https://user-images.githubusercontent.com/33514300/90413157-4dbcd480-e0d8-11ea-943f-f3889ec194c2.png)

**Comment by rizalord** [comment]
You need to pass an id as a parameter

for example as in your case: 
[http://komikcast-rest-api.herokuapp.com/komik?id=i-am-player-who-suck-alone](http://komikcast-rest-api.herokuapp.com/komik?id=i-am-player-who-suck-alone)
